"""comentario

Revision ID: 021e4dd423c5
Revises: 536deed0430c
Create Date: 2025-08-04 03:14:00.978405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021e4dd423c5'
down_revision = '536deed0430c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conteudo', sa.String(length=200), nullable=False))
        batch_op.drop_column('comentario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('conteudo')

    # ### end Alembic commands ###
