"""mensagens

Revision ID: 536deed0430c
Revises: d71af944d211
Create Date: 2025-08-04 02:08:53.002781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536deed0430c'
down_revision = 'd71af944d211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=30), nullable=False))

    # ### end Alembic commands ###
