"""perfil

Revision ID: 772d302d9e9e
Revises: fb2b76dbcd32
Create Date: 2025-07-28 02:59:05.230061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772d302d9e9e'
down_revision = 'fb2b76dbcd32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=512), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('valido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('perfil')

    op.drop_table('tokens')
    # ### end Alembic commands ###
