"""lalala

Revision ID: 7f0eb3c5d7e5
Revises: 772d302d9e9e
Create Date: 2025-07-30 14:02:50.487166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0eb3c5d7e5'
down_revision = '772d302d9e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.alter_column('comentario',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('autor',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.alter_column('autor',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('comentario',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
