"""alteracoes1

Revision ID: 85ea967a6b69
Revises: 021e4dd423c5
Create Date: 2025-08-20 00:36:37.521464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ea967a6b69'
down_revision = '021e4dd423c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=True))
        batch_op.drop_column('data_hora')

    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=False))
        batch_op.drop_column('data_hora')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora', sa.DATETIME(), nullable=True))
        batch_op.drop_column('data_criacao')

    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora', sa.DATETIME(), nullable=True))
        batch_op.drop_column('data_criacao')

    # ### end Alembic commands ###
