"""Criação inicial

Revision ID: d71af944d211
Revises: 
Create Date: 2025-08-04 02:01:37.648889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71af944d211'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=30), nullable=True),
    sa.Column('perfil', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('conteudo', sa.String(length=200), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('autor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=512), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('valido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comentario', sa.String(length=200), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('autor', sa.Integer(), nullable=False),
    sa.Column('mensagem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['mensagem_id'], ['mensagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios')
    op.drop_table('tokens')
    op.drop_table('mensagens')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
